version: '2.0'

services:
  api:
   container_name: "imovel_api"
   build: .
   ports:
    - "3000:3000"
   volumes:
     - .:/home/imovel
     - /home/imovel/node_modules

  database:
    container_name: imovel_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

